
--CREATE DATABASE LOCACAO

CREATE TABLE CLIENTE (
	CLICOD INT PRIMARY KEY IDENTITY NOT NULL,
	CLICPF VARCHAR(11) NULL,
	CLINOM VARCHAR(50) NULL
)

CREATE TABLE LOCACAO (
	LOCCOD INT PRIMARY KEY IDENTITY NOT NULL,
	VEICOD INT NULL,
	CLICOD INT NULL,
	LOCVLRDIA DECIMAL NULL,
	LOCDAT DATETIME NULL,
	LOCDATDEV DATETIME NULL,
	FOREIGN KEY (CLICOD) REFERENCES CLIENTE(CLICOD)
)

CREATE TABLE VEICULO (
	VEICOD INT PRIMARY KEY IDENTITY NOT NULL,
	VEIPLC VARCHAR(7) NULL,
	VEIDES VARCHAR(50) NULL,
	LOCCOD INT NULL,
	FOREIGN KEY (LOCCOD) REFERENCES LOCACAO(LOCCOD)
)
