
--CREATE DATABASE LOCACAO

CREATE TABLE CLIENTE (
	CLICOD INT PRIMARY KEY IDENTITY NOT NULL,
	CLICPF VARCHAR(11) NULL,
	CLINOM VARCHAR(50) NULL
)

CREATE TABLE VEICULO (
	VEICOD INT PRIMARY KEY IDENTITY NOT NULL,
	VEIPLC VARCHAR(7) NULL,
	VEIDES VARCHAR(50) NULL
)

CREATE TABLE LOCACAO (
	LOCCOD INT PRIMARY KEY IDENTITY NOT NULL,
	VEICOD INT NULL,
	CLICOD INT NULL,
	LOCDAT DATETIME NULL,
	LOCDATDEV DATETIME NULL,
	LOCVLRDIA DECIMAL NULL,
	FOREIGN KEY (CLICOD) REFERENCES CLIENTE(CLICOD),
	FOREIGN KEY (VEICOD) REFERENCES VEICULO(VEICOD)
)